/******************************************************************************
 * Copyright (c) 2019, Xilinx, Inc.
 * Copyright (c) 2025, AMD, Inc.
 * All rights reserved.
 *
 *	Redistribution and use in source and binary forms, with or without
 *	modification, are permitted provided that the following conditions are met:
 *
 *	1.	Redistributions of source code must retain the above copyright notice,
 *		 this list of conditions and the following disclaimer.
 *
 *	2.	Redistributions in binary form must reproduce the above copyright
 *			notice, this list of conditions and the following disclaimer in the
 *			documentation and/or other materials provided with the distribution.
 *
 *	3.	Neither the name of the copyright holder nor the names of its
 *			contributors may be used to endorse or promote products derived from
 *			this software without specific prior written permission.
 *
 *	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *	AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *	PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *	OR BUSINESS INTERRUPTION). HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *	WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *	OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *	ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 * @author	Giulio Gambardella <giuliog@xilinx.com>
 * @author	Tobias Alonso <tobiasa@xilinx.com>
 * @author	Thomas B. Preußer <thomas.preusser@amd.com>
 ******************************************************************************/
#ifndef POOL_HPP
#define POOL_HPP

#include <type_traits>
#include <limits>
#include <algorithm>

#include <hls_stream.h>
#include <hls_vector.h>


/*!
 * \brief PoolFunction: General contract for pool functions.
 *
 * This class itself has no formal significance for the implementation
 * of the pool function. It provides a guidence for specific pool function to be used in Pool_batch
 * 
 * \tparam  TO  Datatype of the output generated by the pool function
 * \tparam  TA  Datatype of the internal accumulation in the pool function
 */
template<typename  TO, typename  TA = TO>
class PoolFunction {
public:
	using  accu_t   = TA;
	using  output_t = TO;

public:
	/*!
	 * \brief  Returns the value for accumulator initialization.
	 */
	TA init() const {
#pragma HLS inline
		return	TA(0);
	}

	/*!
	 * \brief  Computes the pooling algorithm (e.g., max, avg, sum).
	 * \param accu	Value from preceding iterations.
	 * \param x     Input value to be absorbed.
	 */
	 template<typename  TI>
	 void pool(TA &accu, TI const &x) const;

	 /*!
	 * \brief  Derives ultimate output from accumulator value.
	 * \param accu	Value from concluded iterations.
	 */
	TO activate(TA const &accu) const {
#pragma HLS inline
		return  accu;
	}

}; // class PoolFunction


/*!
 * \brief MaxPoolFunction: Implementing max pool.
 */
template<typename T>
class MaxPoolFunction : public PoolFunction<T> {
public:
	T init() const {
#pragma HLS inline
		return	std::numeric_limits<T>::min();
	}
	template<typename  TI>
	void pool(T &accu, TI const &x) const {
#pragma HLS inline
		accu = std::max(accu, x);
	}

}; // class MaxPoolFunction

template<typename  E, size_t  N>
class MaxPoolFunction<hls::vector<E, N>> : public PoolFunction<hls::vector<E, N>> {
	using  T = hls::vector<E, N>;

public:
	// Broadcast initialization
	T init() {
#pragma HLS inline
		return  T(std::numeric_limits<E>::min());
	}

	// Elementwise maximum rather than lexicographic input selection
	template<typename  TI>
	void pool(T &a, TI const &b) {
#pragma HLS inline
		for(size_t  i = 0; i < N; i++) {
#pragma HLS unroll
			a[i] = std::max(a[i], b[i]);
		}
	}

}; // class MaxPoolFunction<hls::vector>


/*!
 * \brief AvgPoolFunction: Implementing avg pool.
 */
template<typename  E, typename F, size_t  N>
class AvgPoolFunction : public PoolFunction<hls::vector<E,N>, hls::vecotr<T,N>> {
public:
	template<typename  E, typename F, size_t N>
	void pool(hls::vector<F,N> &accu, hls::vector<E,N> const &x) const {
#pragma HLS inline
		for(size_t i=0; i<N; i++) {
#pragma HLS unroll
			accu[i] += x[i];
		}
	}
	hls::vector<F,N> activate(hls::vector<F,N> const &accu) const {
		hls::vector<F,N> tmp;
#pragma HLS inline
		for(size_t i=0; i<N; i++) {
			tmp[i] = accu[i]/N;
#pragma HLS unroll
		}
		return  tmp;
	}

}; // class AvgPoolFunction
   
/*!
 * \brief AvgPoolFunction: Implementing avg pool for hls::vector.
 */
template<typename  TO, typename  TA,  size_t  N>
class AvgPoolFunction : public PoolFunction<TO, TA> {
public:
	template<typename  TI>
	void pool(TA &accu, TI const &x) const {
#pragma HLS inline
			accu += x;
	}
	TO activate(TA const &accu) const {
#pragma HLS inline
		return  accu/N;
	}

}; // class AvgPoolFunction


template<typename  T>
using  AccPoolFunction = AvgPoolFunction<T, T, 1>;


/*!
 * \brief QuantAvgPoolFunction: Avg pool with shift instead of division.
 */
template<typename  TO, typename  TA, size_t  SHIFT>
class QuantAvgPoolFunction : public AvgPoolFunction<TO, TA, 0> {
public:
	TO activate(TA const &accu) const {
#pragma HLS inline
		return	TO(accu >> SHIFT);
	}
}; // class QuantAvgPoolFunction

//===========================================================================
// Operator Top-Level Function

/**
 * The function implements generic pooling and works in conjuction with a
 * sliding window unit performing im2col on the input data, which enables
 * generic kernel and stride values. Parallel independent reduction lanes
 * are implemented by the passed Pool<> functor when TI and TO are
 * hls::vector types.
 *
 * @param src  Input stream
 * @param dst  Output stream
 * @param fct  Pooling functor (Max, Avg, Sum, ...)
 */
template<
	size_t  ISIZE, // Number of input strobes
	size_t  K,     // Kernel size: Number of inputs reduced to one output
	typename TI,   // [inferred] Input data type
	typename TO,   // [inferred] Output data type
	typename F     // [inferred] Pool<TO, TA=TO> functor type
>
void Pool_batch(
	hls::stream<TI> &src,
	hls::stream<TO> &dst,
	F &&fct
) {
	static_assert(ISIZE%K == 0, "Kernel size must divide input size.");

	typename std::remove_reference_t<F>::accu_t  accu;
#pragma HLS ARRAY_PARTITION variable=accu complete dim=0

	// everything merged into a common iteration space (one "big" loop instead
	// of smaller nested loops) to get the pipelining the way we want
	size_t  k = 0;
	for(size_t  i = 0; i < ISIZE; i++) {
#pragma HLS pipeline II=1 style=flp
		if(k == 0)  accu = fct.init();
		fct.pool(accu, src.read());
		if(++k == K) {
			dst.write(fct.activate(accu));
			k = 0;
		}
	}
}

#endif
